
services:
  keycloak-db:
    image: postgres:17.2
    container_name: spring-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: spring-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_PROXY: edge
    command: >
      start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./import:/opt/keycloak/data/import

volumes:
  keycloak-db-data: